openpharma/mmrm

.gitignore, design/TMB/TMB_mixed.R, design/TMB/TMB_mixed.cpp, design/TMB/TMB_mmrm.Rmd, design/TMB/TMB_mmrm.cpp, design/TMB/TMB_mmrm2.cpp, design/TMB/TMB_mmrm3.cpp, design/TMB/check_autodiff.R, design/TMB/check_autodiff.cpp, design/TMB/sas_log.txt
=> 24: Design with TMB

.github/workflows/check.yaml, _pkgdown.yml
Bootstrap 5 gives search capabilities and a much cleaner UI.
=> Use bootstrap 5 for documentation

.github/workflows/check.yaml, DESCRIPTION, man/h_quad_form.Rd, man/mmrm_methods.Rd, man/mmrm_tmb_methods.Rd
Enable auto-updates of man pages and code style.
=> Enable man pages and code style auto-updates

DESCRIPTION, NEWS.md
=> 86: update NEWS

R/emmeans.R, inst/WORDLIST, man/emmeans_support.Rd, vignettes/introduction.Rmd
Have created a first draft of the introduction as specified in the issue #56.
=> 56 add introduction to introduction vignette @pre-release

DESCRIPTION, NEWS.md, R/emmeans.R, inst/WORDLIST, man/emmeans_support.Rd, vignettes/introduction.Rmd
=> Initial release

.gitignore
well, ignore windows bianries (.dll) : )
see #98
=> ignore windows binaries

.github/workflows/docs.yaml, .github/workflows/release.yaml
Adds workflow dispatch events so one can run all workflows manually at any time.
=> Add dispatchers for workflows

vignettes/introduction.Rmd
Update vignette to show use of dedicated extraction function
=> Use VarCorr extraction function in Vignette

R/data.R, design/SAS/sas_weighted.R, design/SAS/sas_weighted.txt, man/fev_data.Rd, tests/testthat/test-emmeans.R
=> 117: test emmeans for weighted MMRM

.pre-commit-config.yaml, DESCRIPTION, NEWS.md, R/utils.R, design/design_fit.Rmd, inst/WORDLIST, man/free_cores.Rd, man/mmrm-package.Rd, mmrm.Rproj, vignettes/algorithm.Rmd, vignettes/covariance.Rmd, vignettes/introduction.Rmd, vignettes/package_structure.Rmd
=> 126: prep for CRAN submission

DESCRIPTION, inst/WORDLIST, man/mmrm-package.Rd
=> forgot Kevin

.pre-commit-config.yaml, DESCRIPTION, NEWS.md, README.Rmd, README.md, man/mmrm-package.Rd
=> 143: minor fixes for CRAN release

DESCRIPTION, NEWS.md, man/mmrm-package.Rd
=> fix URL in description

_pkgdown.yml
better font/bg contrast and less dependencies #154
=> switch to default bs theme

NEWS.md, R/fit.R, R/tmb.R, man/mmrm.Rd, tests/testthat/test-tmb.R, vignettes/algorithm.Rmd, vignettes/introduction.Rmd
=> 168: Check that we receive unique time points per subject

staged_dependencies.yaml
=> rm_mmrm_frm_staged_deps

.github/CONTRIBUTING.md
=> update contributing guide

src/chol_derivative.h, src/utils.h
=> fix warnings

.github/workflows/check.yaml, DESCRIPTION, NEWS.md, R/component.R, R/fit.R, R/kenwardroger.R, R/tmb.R, R/utils.R, README.Rmd, README.md, inst/WORDLIST, man/component.Rd, man/h_get_optimizers.Rd, man/h_var_adj.Rd, man/mmrm.Rd, man/mmrm_control.Rd, tests/testthat/_snaps/krcomp.md, tests/testthat/test-component.R, tests/testthat/test-fit.R, tests/testthat/test-krcomp.R, tests/testthat/test-tmb.R, vignettes/introduction.Rmd, vignettes/kenward.Rmd
=> 202: Polishing before CRAN release [skip vbump]

DESCRIPTION, NEWS.md, inst/REFERENCES.bib, inst/WORDLIST, vignettes/introduction.Rmd, vignettes/kenward.Rmd, vignettes/package_structure.Rmd, vignettes/satterthwaite.Rmd
=> 204: fix check notes as much as possible [skip vbump]

DESCRIPTION, NEWS.md, tests/testthat/test-fit.R
=> 206: skip flaky test on CRAN

NEWS.md, R/fit.R, R/tmb.R, inst/WORDLIST, man/mmrm.Rd, tests/testthat/test-fit.R, tests/testthat/test-tmb.R
close #237 
na.action is always na.omit after the update
=> fix na errors

.github/workflows/docs.yaml, .github/workflows/release.yaml
Fixes issue reported [here](https://github.com/openpharma/mmrm/pull/235#issuecomment-1432663383).
=> Fix pkgdown workflow

R/cov_struct.R, R/fit.R, R/tmb.R, man/as.cov_struct.Rd, man/covariance_types.Rd, man/mmrm.Rd, tests/testthat/test-tmb.R, vignettes/introduction.Rmd
closes #220 
- Inserts a check and corresponding error message in R/tmb.R, within the fit_mmrm() function; add a corresponding test in test-tmb.R under 'misc'.
- Updates the documentation in R/fit.R for mmrm(), in cov_struct.R for cov_types, and in the intro vignette.
=> 220 time as factor

R/empirical.R, src/empirical.cpp, src/exports.cpp
accidentally working on two branch
=> potential update following paper suggest

R/tmb-methods.R, tests/testthat/test-tmb-methods.R
=> fix issue of aliased variable

src/chol_cache.h, src/mmrm.cpp, src/test-chol_cache.cpp
close #273 
key changes
1. create a class of chol_by_group to reduce code in main
2. use unique pointers to avoid new/delete
=> simplify objective function

DESCRIPTION, R/cov_struct.R, R/utils.R, tests/testthat/test-cov-struct.R, tests/testthat/test-fit.R, tests/testthat/test-interop-parsnip.R
=> allow covariance to be formula

DESCRIPTION, src/chol_cache.h, src/derivatives.h, src/empirical.cpp, src/kr_comp.cpp, src/mmrm.cpp, src/predict.cpp, src/test-chol_cache.cpp, src/test-derivatives.cpp
close #272 
initial attempt to clean up code
=> 272 reduce replicated

src/empirical.cpp, src/jacobian.cpp, src/kr_comp.cpp, src/predict.cpp, src/test-utils.cpp, src/utils.h
=> clean up code

vignettes/predict.Rmd
close #308 
add the simulation section
=> 308 simulate vig

R/tmb.R, tests/testthat/test-tmb.R
=> add checks of h_mmrm_tmb_check_conv

src/chol_cache.h, src/predict.cpp
=> 331: clean up MacOS clang compiler warnings

R/interop-parsnip.R, R/tmb-methods.R, man/mmrm_tmb_methods.Rd, man/parsnip_add_mmrm.Rd, tests/testthat/test-interop-parsnip.R, tests/testthat/test-tmb-methods.R, vignettes/.subsections/intro-tidymodels.Rmd
=> 342: Add predict template for tidymodels

DESCRIPTION, NEWS.md, R/tmb.R, R/zzz.R, man/check_package_version.Rd, man/h_mmrm_tmb_fit.Rd, man/register_on_load.Rd, tests/testthat/test-fit.R, tests/testthat/test-interop.R, tests/testthat/test-tmb.R
=> 343: Fix CRAN problems

DESCRIPTION, NEWS.md, tests/testthat/test-fit.R
=> 343: simplify tests to avoid spurious CRAN test failures [skip vbump]

DESCRIPTION, NEWS.md, tests/testthat/test-fit.R
=> 343: fix more tests hopefully [skip vbump]

NEWS.md, R/fit.R, man/mmrm_control.Rd
=> swapped CR2 and CR3

vignettes/mmrm_review_methods.Rmd
`nlme::gls()` does not have a `formula` argument.
=> Pass formula as unnamed argument to gls()

R/utils.R, man/emp_start.Rd, tests/testthat/test-fit.R
=> use data instead of full_frame in emp

vignettes/algorithm.Rmd, vignettes/coef_vcov.Rmd, vignettes/introduction.Rmd, vignettes/package_structure.Rmd, vignettes/predict.Rmd, vignettes/subsections/_intro-customizations.Rmd
=> fix vignettes

src/utils.h
close #409 
warnings on data type should be removed now
=> fix cpp warning

vignettes/hypothesis_testing.Rmd
items are not properly rendered in HTML
=> add blank line for items

src/utils.h
=> fix eigen deprecated warning

DESCRIPTION, NEWS.md, man/mmrm-package.Rd, tests/testthat/test-residual.R
closes #374 
Important: only to be merged once CRAN accepts this version
=> add tests for residual.R, bump up version

.github/workflows/rhub.yaml, DESCRIPTION, NEWS.md, vignettes/empirical_wls.Rmd
To enable using https://github.com/r-hub/rhub for `clang18` checks.
=> add rhub workflow

DESCRIPTION, NEWS.md
=> 515: release 0.3.15
