R/tmb.R, design/SAS/sas_antedependence.R, design/SAS/sas_antedependence_ml.txt, design/SAS/sas_antedependence_reml.txt, inst/REFERENCES.bib, inst/WORDLIST, mmrm.Rproj, src/correlation.h, src/test-correlation.cpp, src/test-utils.cpp, src/testthat-helpers.h, src/utils.h, tests/testthat/helper-examples.R, tests/testthat/test-correlation.R, tests/testthat/test-fit.R, tests/testthat/test-tmb.R, vignettes/algorithm.Rmd, vignettes/correlation.Rmd
=> 42: add ante-dependence correlation structure

DESCRIPTION, NEWS.md, R/tmb.R, man/h_mmrm_tmb_data.Rd, man/mmrm-package.Rd, src/covariance.h, src/mmrm.cpp, src/test-covariance.cpp, tests/testthat/test-tmb.R
Closes #69
Previously, `h_mmrm_tmb_data` would store a numeric value which corresponds to a covariance function. This is a somewhat superficial change that provides the covariance type to the model function generator as a string, allowing it to be more meaningful without knowledge of the enum mapping. 
I also added an error condition when the string was unmatched. Previously, an unmatched enum would silently return an empty matrix. This was somewhat guarded against by verifying the condition type in `h_mmrm_tmb_formula_parts`, but perhaps this helps to focus that checking in one place and reduce the need to keep parity between the two bits of code? Of course, if a user would ever need to tease apart `formula_parts` without building a model function, then it's nice to keep the guard in …
=> Handle mapping of covariance type abbreviations to functions within Cpp-level API (Resolves #69)

DESCRIPTION
Not having it results in:
```
Error: processing vignette 'introduction.Rmd' failed with diagnostics:
The 'rmarkdown' package should be declared as a dependency of the 'mmrm' package (e.g., in the  'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'rmarkdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
--- failed re-building ‘introduction.Rmd’
```
=> Add `rmarkdown` to Suggests

R/tmb.R, tests/testthat/test-fit.R, tests/testthat/test-tmb.R, vignettes/covariance.Rmd
close #95 
the typo in [vignettes/covariance.Rmd](https://github.com/openpharma/mmrm/compare/95_typo?expand=1#diff-1a86968857585f8d0d042c84415044f4dd62dd4757fdd8175abc4c6a8e7e5ba0) file is updated
now there is a covariance structure checking include
1. no covariance matrix specified
2. covariance matrix specified multiple times
3. covariance matrix does not take the form  `cs(VISIT|ID)`
=> 95: fix typo and update covariance structure check

README.md
directly link to covariance docs page to make it easier to scope the package from the readme
=> add link to covariance structures in readme

R/fit.R, R/utils.R, man/mmrm.Rd, tests/testthat/test-parallel.R
this sets the default to just 1 core. downstream packages or users can still use free_cores() to manually ask for as many cores as are free
[skip vbump]
=> fix parallel problem

src/init.h
Problem is that `run_testthat_tests` has one argument which was not present before when the templates were created that we used here. This problem showed only up with specific LTO tests.
- See https://github.com/r-lib/testthat/blob/05b07d4353ff0c2ec81e90a7110476b613a1cd2d/inst/include/testthat/testthat.h#L172 for the definition in testthat.
- See https://github.com/r-lib/testthat/issues/1230 for more info.
=> correct run_testthat_tests definition in init.h

tests/testthat/test-fit.R
Closes #177 
The issue suggested skipping tests that required `parallelly`, but I felt like this was a useful test even if not installed and could otherwise be performed just fine.
Instead, I check whether multiple cores are available. If `parallelly` is available it is used to detect a maximum number of cores, but otherwise the tests are run on a minimum 2 cores.
It sounds like the edge cases that `parallelly` addresses are unlikely to be hit during unit testing and a more conservative fallback would be a suitable substitute. 
Tested against an install without `parallelly` installed. As far as I can tell it's just used for `availableCores` and this is the only thing that would be affected.
=> Allow tests to run without `parallelly` installed

DESCRIPTION
Closes #167
Knocking out another easy fix. This is an important one because the version constraints for LinkingTo are applied at install, while the version constraints for Depends/Imports are applied on-load.
Previously, someone could build a version of the package with an older version of TMB, then update TMB to satisfy the on-load version constraint and find that the package breaks due to version used at install.
=> adding version constraint for LinkingTo TMB

tests/testthat/test-fit.R
closes #186 
I'd still like to investigate this to constrain the test a bit more, but as a start I'm just disabling this test.
I'm a bit concerned because the test immediately below this one uses the same optimizer with all the same parameters and expects the same output, so this might just be a stochastic error which we _may_ hit again with the next test. 
If we want to be more mindful about the possibility of some model fits failing during testing, then we might want to build our own context manager that stores a tally of successful or failed model fits, skipping the first few failed fit tests and only failing outright if, for example, >5 models have been fit and >10% ever fail. This would give us some resilience to stochastic failures on CRAN without forcing us to continue skipping any …
=> Skip error-prone tests on Fedora + Clang

R/utils-formula.R, tests/testthat/test-cov-struct.R, tests/testthat/test-fit.R, tests/testthat/test-utils-formula.R
close #261 
on CRAN we don't have this bug as we are using `variable` attribute already
https://github.com/openpharma/mmrm/blob/2fdbb02ca057ab85a6cf2177b459b6c60cabe6dd/R/tmb.R#L147
=> fix bug of interaction only models

simulations/missing-data-benchmarks/R/method/proc-mixed-wrapper.R
Addresses #274: The `PROC MIXED` wrapper function used in the simulation study assessing the impact of missing data erroneously set the degrees of freedom calculation to Kenward-Rogers. It is now set to Satterthwaite, the `mmrm()` default.
=> DDFM option set to SAT instead of KR in PROC MIXED

R/tmb-methods.R, R/utils.R, tests/testthat/test-tmb-methods.R, tests/testthat/test-utils.R
close #287 
changes:
1. NA is allowed in new predict data (gives NA in prediction)
2. order follows the original data
=> allow NA in data for prediction; order preserved

vignettes/covariance.Rmd
This change makes the spatial exponential title consistent with the titles for other covariance structures.
=> DOC: Add missing spatial exponential function name

R/zzz.R, src/chol_cache.h
use make_shared instead of make_unique
also update the `check_package_version` function to avoid errors like
```
Cannot register mmrm for use with parsnip (v1.0.3). Version 1.0.4 to NA required
```
=> fix make_unique

.github/workflows/check.yaml
This is no longer necessary after we updated the way pkgdown documentation is uploaded to `gh-pages` branch. This change has also previously been propagated to other repositories that use the `r.pkg.template` workflows.
=> Don't rerun the check workflow after the Docs workflow finishes

R/tmb.R, man/h_mmrm_tmb_data.Rd, src/chol_cache.h, src/derivatives.h, src/empirical.cpp, src/jacobian.cpp, src/kr_comp.cpp, src/mmrm.cpp, src/predict.cpp, src/test-derivatives.cpp, src/test-utils.cpp, src/utils.h, tests/testthat/test-tmb.R
close #110
current implementation unifies coordinates and visits.
There is an extra data conversion so it is expected there is a small cost.
Average computation time for `FEV1 ~ ARMCD + us(AVISIT|USUBJID)`  on `fev_data` decrease from 37.53347 ms to 37.89274 ms (but still very small and neglectable I think)
In addition, the select matrix is removed but instead use "subset_matrix" functionality
=> unify coordinates and visits_zero_index

staged_dependencies.yaml
this is only needed temporarily for downstream `tern.mmrm` as long as `mmrm` is not yet on CRAN. This should not impact anything else in a negative way.
=> add staged deps

DESCRIPTION, NEWS.md, R/interop-emmeans.R, man/emmeans_support.Rd, vignettes/subsections/_intro-hypothesis_testing.Rmd
[skip vbump]
Based on user question.
=> Improve emmeans doc with pairs / new release (another CRAN submission round)

staged_dependencies.yaml
closes https://github.com/openpharma/mmrm/issues/375
=> 375: remove again staged.dependencies now that we are on CRAN

design/unstructured_optimization.Rmd
part of https://github.com/openpharma/mmrm/issues/380
=> 380: Idea to solve convergence problem

NEWS.md, R/fit.R, tests/testthat/helper-examples.R, tests/testthat/test-fit.R
close #410 
previously the best fit is incorrectly selected.
=> 410 converge

NEWS.md, R/fit.R, R/tmb-methods.R, R/utils.R, tests/testthat/test-fit.R
I can not produce examples that `h_record_all_outputs` that can create a "try-error" object, but only returns `list()` on any error, unless there is some internal `try(expr, silent=T)` in `fit_mmrm` call, however I did not find such things that could potentially return the "try-error" object. any ideas @danielinteractive ?
=> fix issue of h_record_all_outputs

NEWS.md, R/interop-car.R, tests/testthat/test-car.R
close #426 
previously all covariate are treated as factor.
Now there is a additional check for anova, to provide length of unique character values, instead of the nlevels functions to count the levels.
In addition, the data used, is not `component(obj, "full_frame")` (which may contain character variable) now. it is using `model.frame(obj)` to ensure everything is a factor.
The reason is that in most of our analysis we want to ensure that factors are used, to avoid potential issues (like difference in orders of factor that could lead to incorrect predict etc)
=> fix anova error

DESCRIPTION
close #418 
after removing biocview, it seems we don't need bioconductor anymore
=> remove biocVer

NEWS.md, R/tmb.R, tests/testthat/test-fit.R, tests/testthat/test-tmb.R
=> signal non-convergence if theta_vcov is not positive definite

DESCRIPTION, NEWS.md, R/utils.R, inst/WORDLIST, man/mmrm-package.Rd, tests/testthat/test-utils.R
=> add Lukas as contributor, bump up version, polish news

DESCRIPTION, NEWS.md, R/component.R, R/fit.R, man/component.Rd, src/empirical.cpp, tests/testthat/_snaps/tmb-methods.md, tests/testthat/test-component.R, tests/testthat/test-empirical.R, vignettes/coef_vcov.Rmd
This can resolve issue #494. Unit tests are added.
=> return meat per subject when computing empirical covariance matrix of coefficients

vignettes/mmrm_review_methods.Rmd
Tackling issue #511.
`corCAR1` is used to model continuous AR(1) correlation structures and it does only work with integer valued covariates.
Therefore, in the vignette "Comparison with other software", the correlation structure in `gls` calls is changed to `corAR1`. In addition, the non-continuous AR1 correlation structure is also what SAS and {mmrm} use.
=> Fix AR correlation structure in `gls` calls

R/utils.R, tests/testthat/helper-examples.R, tests/testthat/test-mmrm-methods.R
The helper function `h_get_minimal_fit_data()` naively grabbed the lefthand side of the model formula as well as the covariance structure variables and treated them as column names that might be found in `data`. The issue with this is that these elements could be calls rather than just symbols (i.e., `log(x)` instead of just `x`). This pull request extracts names from these elements before looking for them in `data`.
=> make h_get_minimal_fit_data() extract names from calls
